import { getTranslations } from "next-intl/server";

import { IconMaisonRochevalLogo } from "@/shared/components/icons/maison-rocheval-logo";
import { buildPictureSources } from "@/shared/lib/image";

/**
 * The desktop and mobile frames crop the same photo very differently — desktop
 * shows the wide valley, mobile a narrow slice of the lake — so the two crops
 * are shipped as separate files and art-directed at the `md` breakpoint. The
 * assets are generated by scripts/generate-coming-soon-images.mjs.
 */
const desktopImage = buildPictureSources(
  "/images/coming-soon/coming-soon-hero-desktop",
  "jpg",
);
const mobileImage = buildPictureSources(
  "/images/coming-soon/coming-soon-hero-mobile",
  "jpg",
);

const DESKTOP_MEDIA = "(min-width: 768px)";

export async function ComingSoonHeroSection() {
  const t = await getTranslations("comingSoon.hero");

  return (
    <section
      aria-labelledby="coming-soon-title"
      data-slot="coming-soon-hero-section"
      className="relative flex h-dvh w-full flex-col items-center justify-between overflow-hidden bg-canvas py-[54px] md:pb-[120px] md:pt-[84px]"
    >
      <picture className="absolute inset-0 block">
        <source media={DESKTOP_MEDIA} srcSet={desktopImage.avif} type="image/avif" />
        <source media={DESKTOP_MEDIA} srcSet={desktopImage.webp} type="image/webp" />
        <source media={DESKTOP_MEDIA} srcSet={desktopImage.fallback} type="image/jpeg" />
        <source srcSet={mobileImage.avif} type="image/avif" />
        <source srcSet={mobileImage.webp} type="image/webp" />
        <img
          src={mobileImage.fallback}
          alt={t("imageAlt")}
          width={856}
          height={1600}
          sizes="100vw"
          fetchPriority="high"
          loading="eager"
          decoding="async"
          className="size-full object-cover"
        />
      </picture>

      <IconMaisonRochevalLogo
        className="relative h-auto w-[169px] text-ink"
        aria-hidden="true"
        focusable="false"
      />

      <h1
        id="coming-soon-title"
        className="relative font-display text-section-title font-normal text-canvas"
      >
        <span className="sr-only">{t("brand")} — </span>
        {t("message")}
      </h1>
    </section>
  );
}
