import type { Product } from "@/shared/components/composite/product-card";

export const VARIETIES: Product[] = [
  {
    id: "prod_amur",
    handle: "caviar-amur",
    title: "Amur Caviar",
    imageBasePath: "/images/about-product/species-amur",
    imageAlt: "Open Maison Rocheval Amur caviar tin",
    eyebrow: "Patrimoine",
    species: "Huso Dauricus",
    profile: "Rich · Creamy · Long finish",
    description: "Exceptional pearls from the Amur river basin. Dark grey to golden olive, offering a complex walnut and creamy texture finish.",
  },
  {
    id: "prod_kaluga",
    handle: "caviar-kaluga",
    title: "Kaluga Caviar",
    imageBasePath: "/images/about-product/species-kaluga-hybrid",
    imageAlt: "Open Maison Rocheval Kaluga caviar tin",
    eyebrow: "Patrimoine",
    species: "Huso Dauricus",
    profile: "Rich · Creamy · Long finish",
    description: "Known as the river beluga. Extra-large pearls with warm bronze reflections, rich butter and oceanic notes.",
  },
  {
    id: "prod_hybrid",
    handle: "caviar-russian-hybrid",
    title: "Russian Hybrid Caviar",
    imageBasePath: "/images/about-product/species-russian-sturgeon",
    imageAlt: "Open Maison Rocheval Russian Hybrid caviar tin",
    eyebrow: "Patrimoine",
    species: "Acipenser Gueldenstaedtii",
    profile: "Silky · Clean · Fresh",
    description: "A refined crossing of Acipenser gueldenstaedtii and baerii. Intense olive pearls with a brilliant, robust saline finish.",
  },
  {
    id: "prod_expression",
    handle: "expression",
    title: "L’Expression",
    imageBasePath: "/images/home/product-expression",
    imageAlt: "Open Maison Rocheval L’Expression caviar tin",
    eyebrow: "Réserve",
    species: "Kaluga Hybrid",
    profile: "Rounded · Precise · Nutty",
    description: "The signature expression of the Maison, selected for balance and an exceptionally clean finish.",
  },
  {
    id: "prod_harmonie",
    handle: "harmonie",
    title: "Harmonie",
    imageBasePath: "/images/home/product-harmonie",
    imageAlt: "Open Maison Rocheval Harmonie caviar tin",
    eyebrow: "Assemblage",
    species: "Russian Hybrid",
    profile: "Silky · Soft · Fruity",
    description: "Named for balance and defined by fruit, with a supple grain and delicate persistence.",
  },
];
