import type { ProductsProduct } from "../types/products.type";

export const PRODUCTS = [
  {
    id: "product-amur",
    handle: "caviar-amur",
    imageBasePath: "/images/about-product/species-kaluga-hybrid",
    imageHeight: 550,
    imageWidth: 400,
    plumbCardId: "component-22",
    plumbImageId: "image-5-2",
    translationKey: "amur",
  },
  {
    id: "product-kaluga",
    handle: "caviar-kaluga",
    imageBasePath: "/images/about-product/species-amur",
    imageHeight: 550,
    imageWidth: 400,
    plumbCardId: "component-22-2",
    plumbImageId: "image-5-4",
    translationKey: "kaluga",
  },
  {
    id: "product-russian-hybrid",
    handle: "caviar-russian-hybrid",
    imageBasePath: "/images/about-product/species-russian-sturgeon",
    imageHeight: 550,
    imageWidth: 400,
    plumbCardId: "component-22-3",
    plumbImageId: "image-5-6",
    translationKey: "russianHybrid",
  },
  {
    id: "product-expression",
    handle: "expression",
    imageBasePath: "/images/home/product-expression",
    imageHeight: 550,
    imageWidth: 400,
    plumbCardId: "component-22-4",
    plumbImageId: "image-5-8",
    translationKey: "expression",
  },
  {
    id: "product-harmonie",
    handle: "harmonie",
    imageBasePath: "/images/home/product-harmonie",
    imageHeight: 550,
    imageWidth: 400,
    plumbCardId: "component-22-5",
    plumbImageId: "image-5-10",
    translationKey: "harmonie",
  },
] satisfies readonly ProductsProduct[];
